In [1]:
import pandas as pd
import numpy as np
import csv
import random
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [137]:
with open('custpmer_churn.csv', 'w', newline = '') as csvfile:
  fieldnames = (['ID', 'Age','Gender', 'Tenure', 'Balance', 'Num_Products', 'Credit_Score', 'Churn'])
  writer = csv.DictWriter(csvfile, fieldnames = fieldnames)
  writer.writeheader()
  for i in range(9000):
    writer.writerow({'ID': i+1, 'Age':random.randint(25,60), 'Gender':random.choice(['Male', 'Female']), 'Tenure':random.randint(16,40),
                     'Balance': random.randint(500, 5000), 'Num_Products': random.randint(1, 5), 'Credit_Score': random.randint(500, 850),
                     'Churn': random.choice(['Yes', 'No'])})

In [262]:
cust_file = pd.read_csv('custpmer_churn.csv')
cust_file.head(15)

    ID  Age  Gender  Tenure  Balance  Num_Products  Credit_Score Churn
0    1   43    Male      34     3972             5           815   Yes
1    2   60    Male      24     2395             3           825    No
2    3   33  Female      25     1466             1           783    No
3    4   49    Male      26      950             1           775   Yes
4    5   41  Female      40      566             2           757    No
5    6   50  Female      39     1624             2           818   Yes
6    7   56  Female      27     1881             2           661   Yes
7    8   41    Male      24     4227             1           824    No
8    9   45    Male      26     2061             2           537    No
9   10   34  Female      23     2406             3           599   Yes
10  11   35    Male      34     4086             2           734   Yes
11  12   37    Male      40     1571             3           725   Yes
12  13   29    Male      37     2418             3           573    No
13  14   36    Male      22      612             3           658    No
14  15   47  Female      18     4807             5           829    No

In [263]:
cust_file.isnull().sum()

ID              0
Age             0
Gender          0
Tenure          0
Balance         0
Num_Products    0
Credit_Score    0
Churn           0
dtype: int64

In [264]:
cust_file.shape

(9000, 8)

In [265]:
cust_file.describe()

,ID,Age,Tenure,Balance,Num_Products,Credit_Score
count,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,4500.500000,42.574444,28.006556,2765.840889,2.982444,675.675889
std,2598.220545,10.341282,7.274579,1292.462757,1.411273,101.547933
min,1.000000,25.000000,16.000000,500.000000,1.000000,500.000000
25%,2250.750000,34.000000,22.000000,1667.750000,2.000000,587.000000
50%,4500.500000,43.000000,28.000000,2766.500000,3.000000,677.000000
75%,6750.250000,51.000000,34.000000,3886.000000,4.000000,763.000000
max,9000.000000,60.000000,40.000000,5000.000000,5.000000,850.000000

In [266]:
cust_file['Credit_Score'].value_counts()

Credit_Score
837    40
846    39
819    39
551    38
556    37
       ..
599    16
587    16
765    14
648    14
675     9
Name: count, Length: 351, dtype: int64

In [267]:
cust_file['Churn'].value_counts()

Churn
No     4554
Yes    4446
Name: count, dtype: int64

In [144]:
from sklearn.preprocessing import LabelEncoder
Label_Encoder = LabelEncoder

In [268]:
cust_file.groupby('Churn').mean(numeric_only = True)

,ID,Age,Tenure,Balance,Num_Products,Credit_Score
Churn,,,,,,
No,4524.218709,42.608037,28.086517,2774.959596,2.974967,676.237154
Yes,4476.205128,42.540036,27.924651,2756.500675,2.990103,675.100990

In [298]:
X = cust_file.drop(columns = ['Gender', 'Churn'])
Y = cust_file['Churn']
print(X)
print(Y)

        ID  Age  Tenure  Balance  Num_Products  Credit_Score
0        1   43      34     3972             5           815
1        2   60      24     2395             3           825
2        3   33      25     1466             1           783
3        4   49      26      950             1           775
4        5   41      40      566             2           757
...    ...  ...     ...      ...           ...           ...
8995  8996   26      30     4970             5           738
8996  8997   47      30     3766             1           570
8997  8998   42      34      557             1           533
8998  8999   54      40     2330             3           814
8999  9000   51      34     3143             5           694

[9000 rows x 6 columns]
0       Yes
1        No
2        No
3       Yes
4        No
       ...
8995     No
8996     No
8997    Yes
8998     No
8999    Yes
Name: Churn, Length: 9000, dtype: object

In [299]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3, stratify = Y, random_state = 42)

In [300]:
print(X.shape, X_train.shape, X_test.shape)

(9000, 6) (6300, 6) (2700, 6)

In [301]:
model = LogisticRegression()

In [302]:
print(X_train)

        ID  Age  Tenure  Balance  Num_Products  Credit_Score
4934  4935   49      25     2705             5           710
8557  8558   52      34     2574             5           543
287    288   45      30     4426             2           809
8792  8793   56      17     2236             5           559
5671  5672   27      33     2809             2           510
...    ...  ...     ...      ...           ...           ...
145    146   35      22     4394             4           620
3938  3939   49      39     4234             3           842
7920  7921   34      30     1563             4           628
4984  4985   58      19     4415             2           552
7870  7871   46      19     2159             4           624

[6300 rows x 6 columns]

In [303]:
print(Y_train)

4934     No
8557     No
287      No
8792     No
5671    Yes
       ...
145     Yes
3938    Yes
7920    Yes
4984    Yes
7870    Yes
Name: Churn, Length: 6300, dtype: object

In [320]:
model = LogisticRegression(solver='lbfgs', max_iter=200)  # Increase max_iter
model.fit(X_train, Y_train)

LogisticRegression(max_iter=200)

In [322]:
X_train_prediction = model.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print(train_data_accuracy)

0.5050793650793651

In [323]:
X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print(testing_data_accuracy)

0.5066666666666667

In [308]:
cust_file = pd.read_csv('custpmer_churn.csv')
cust_file.head(25)

    ID  Age  Gender  Tenure  Balance  Num_Products  Credit_Score Churn
0    1   43    Male      34     3972             5           815   Yes
1    2   60    Male      24     2395             3           825    No
2    3   33  Female      25     1466             1           783    No
3    4   49    Male      26      950             1           775   Yes
4    5   41  Female      40      566             2           757    No
5    6   50  Female      39     1624             2           818   Yes
6    7   56  Female      27     1881             2           661   Yes
7    8   41    Male      24     4227             1           824    No
8    9   45    Male      26     2061             2           537    No
9   10   34  Female      23     2406             3           599   Yes
10  11   35    Male      34     4086             2           734   Yes
11  12   37    Male      40     1571             3           725   Yes
12  13   29    Male      37     2418             3           573    No
13  14   36    Male      22      612             3           658    No
14  15   47  Female      18     4807             5           829    No
15  16   31    Male      19     2889             2           652   Yes
16  17   43  Female      17     1911             5           564   Yes
17  18   39    Male      36     1395             5           511   Yes
18  19   59    Male      29      923             2           833   Yes
19  20   51    Male      34     3703             1           585    No
20  21   41    Male      28     1478             1           656    No
21  22   59  Female      26     2436             5           728   Yes
22  23   46  Female      21     2296             3           785   Yes
23  24   43  Female      29     2031             3           507    No
24  25   54  Female      16     3821             3           650    No

In [324]:
input_data = (22, 59, 26, 2436, 5, 728)	
input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

prediction = model.predict(input_data_reshaped)
print(prediction)

['Yes']

C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [315]:
if (prediction[0] == 'Yes'):
    print('Customer Churned')
else:
    print('Customer Not Churned')

Customer Churned